apiVersion: v1
kind: Service
metadata:
  name: cs3219-db
  namespace: cs3219
spec:
  type: ClusterIP
  selector:
    app: cs3219-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 31306
